version: '3.8'

services:
  notion-task-manager:
    build: .
    image: nickborgers/notion-home-task-manager:latest
    container_name: notion-home-task-manager
    volumes:
      # Mount the config file
      - ./notion_config.yaml:/app/notion_config.yaml:ro
      # Mount logs directory for persistence
      - ./logs:/app/logs
    environment:
      # You can override config with environment variables if needed
      - PYTHONUNBUFFERED=1
      # Add your Notion integration token here or use a .env file
      # - NOTION_INTEGRATION_TOKEN=your_integration_token_here
    # Run continuously with restart policy
    restart: unless-stopped
    # For development, you can override the command to run once
    # command: ["python", "scripts/weekly_rollover/create_active_tasks_from_templates.py"] 